kolor=input("podaj kolor: ")
mnogirzeczownik=input("podaj rzeczownik w formie mnogiej: ")
celebryta=input("podaj celebrryte: ")
print("Róże są " + kolor)
print(mnogirzeczownik +" są niebiesie")
print("Kocham " + celebryta)
